name: Docker image

on:
  push:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Configure AWS credentials (OIDC)
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::833899002257:role/github-actions-ecr
            aws-region: sa-east-1

        - name: Login no Amazon ECR
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build and Push Docker image
        env:
          ECR_REGISTRY: 833899002257.dkr.ecr.sa-east-1.amazonaws.com
          ECR_REPOSITORY: teste-pipeline
          IMAGE_TAG: latest